#!/usr/bin/env bash
#  transfers a file from our client to a server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
