#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 408670-web-01 54.86.220.157:80 check
    server 408670-web-02 100.26.212.86:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
# #!/usr/bin/env bash
# #Install and configure HAproxy on your lb-01 server.

# #install part
# sudo apt-get install -y software-properties-common
# sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
# sudo apt-get update -y
# sudo apt-get install -y haproxy=2.0.\*

# #configration
# sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' <<EOF
# global
#     log /dev/log local0
#     log /dev/log local1 notice
#     chroot /var/lib/haproxy
#     stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
#     stats timeout 30s
#     user haproxy
#     group haproxy
#     daemon

# defaults
#     log global
#     mode http
#     option httplog
#     option dontlognull
#     timeout connect 5000
#     timeout client 50000
#     timeout server 50000

# frontend http_front
#     bind *:80
#     stats uri /haproxy?stats
#     default_backend http_back

# backend http_back
#     balance roundrobin
#     server 408670-web-01 54.86.220.157:80 check
#     server 408670-web-02 100.26.212.86:80 check
# EOF

# echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# sudo service haproxy start
