#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#install part
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update -y
sudo apt-get install -y haproxy=2.0.\*

#configration
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
sudo vim /etc/haproxy/haproxy.cfg
echo "
frontend sarahgad
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 408670-web-01 54.86.220.157 check
    server 408670-web-02 100.26.212.86 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
