#!/usr/bin/env bash
#Write a Bash script that configures a server to the above requirements
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill "$(pgrep 'nginx' | head -1)"
