#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID

delete(){
    rm "$File_script"
}

File_script="/var/run/myscript.pid"
echo "$$" > "$File_script"

trap "echo 'To infinity and beyond' && delete && exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "delete && exit" SIGQUIT

while true; do
echo "To infinity and beyond"
sleep 2
done
