#!/usr/bin/env bash
#using while loop 4-if_9_say_hi
number=0
while [ $number -lt 10 ]
do
    if [ $number -eq 3 ]; then
        echo "bad luck"
    elif [ $number -eq 7 ]; then
     echo "good luck"
    else 
     echo "Best School"
        fi
    number=$(( number+1 ))
done
