#!/usr/bin/env bash
#using while loop 4-if_9_say_hi
number=1
while [ $number -lt 21 ]
do
    echo $number
    case "$number" in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    esac
    number=$(( number+1 ))
done
